# Generated by Django 6.0.2 on 2026-02-10 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_source_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='data_type',
            field=models.CharField(choices=[('physical', 'Physical Survey'), ('ofc', 'OFC Record')], default='physical', max_length=20),
        ),
    ]
