# Generated by Django 6.0.2 on 2026-02-10 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_place_data_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='block',
            field=models.CharField(db_index=True, default='Nihal Singh Wala', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.CharField(db_index=True, default='Moga', max_length=100),
        ),
        migrations.AddField(
            model_name='place',
            name='state',
            field=models.CharField(db_index=True, default='Punjab', max_length=100),
        ),
    ]
