# Generated by Django 6.0.2 on 2026-02-11 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_place_block_place_district_place_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='block',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='district',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='place',
            name='state',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
