# Generated by Django 6.0.2 on 2026-02-10 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_geom'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='source_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
