# Generated by Django 6.0.2 on 2026-02-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_place_block_alter_place_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='line_color',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
